name: wc_form_validators
description: A Flutter plugin to validate forms with utility functions. It can validate emails, regex, character limits and many more.
version: 1.0.1
homepage: https://github.com/aarajput/flutter_form_validators

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
